version: '3.8'
services:
  gobot:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - gobot-db
    volumes:
        - ./migrations:/app/migrations
  gobot-db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
    networks:
      - pet-help
    volumes:
      - ./database:/var/lib/postgresql